# Generated by Django 4.2.7 on 2023-11-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='acticle_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add picture to article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
