# Generated by Django 4.2.7 on 2023-11-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_acticle_image_alter_article_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='acticle_image',
            new_name='article_image',
        ),
    ]
